"""Tests for the random card-spec generator."""

from __future__ import annotations

from collections import Counter

from moxify_ocr.data.cardconjurer_specs import generate_specs, make_spec


def test_make_spec_is_deterministic_with_seed() -> None:
    a = make_spec(seed=42)
    b = make_spec(seed=42)
    assert a == b


def test_make_spec_produces_valid_label() -> None:
    spec = make_spec(seed=0)
    # Set is a 2-6 char uppercase alphanumeric string. Hybrid generation:
    # majority drawn from real Scryfall codes, minority generated by
    # frequency-weighted random sampling for future-set generalization.
    assert 2 <= len(spec.info_set) <= 6
    assert spec.info_set.isupper()
    assert spec.info_set.isalnum()
    # Rarity is a single uppercase letter.
    assert spec.info_rarity in {"C", "U", "R", "M", "S", "P"}
    # Language is from our supported set.
    assert spec.info_language in {"EN", "DE", "FR", "ES", "IT", "PT", "JA", "KO", "ZH", "RU"}


def test_set_codes_include_real_scryfall_codes() -> None:
    """Majority of synthetic codes should match real Scryfall codes.

    The model learns much better when the character distribution it trains
    on matches the distribution it sees in production. v3_v2 used pure
    random codes and hit only 23% test set_code_accuracy because the visual
    patterns didn't match real cards.
    """
    from moxify_ocr.data._real_set_codes import REAL_SET_CODES

    real_set = set(REAL_SET_CODES)
    specs = list(generate_specs(n=1000, seed=0))
    real_count = sum(1 for s in specs if s.info_set in real_set)
    # Target: ~70% real. Allow wide tolerance for distribution variance.
    assert 600 < real_count < 800, (
        f"{real_count}/1000 codes match real Scryfall set codes "
        "(expected ~700; suggests hybrid sampling not wired correctly)"
    )


def test_set_codes_include_random_codes_for_generalization() -> None:
    """Some fraction of codes must be NOT in the real list.

    The whole point of the random slice is to teach character-level OCR for
    sets Wizards hasn't shipped yet. If 100% match real codes, we've reverted
    to a closed vocabulary.
    """
    from moxify_ocr.data._real_set_codes import REAL_SET_CODES

    real_set = set(REAL_SET_CODES)
    specs = list(generate_specs(n=1000, seed=0))
    novel_count = sum(1 for s in specs if s.info_set not in real_set)
    # Target ~30% novel. Allow wide tolerance.
    assert 200 < novel_count < 400, (
        f"{novel_count}/1000 codes are novel (not in real Scryfall set) "
        "(expected ~300; suggests random generation slice missing or wrong)"
    )


def test_set_codes_include_alphanumeric_codes() -> None:
    """~33% of real Scryfall codes contain a digit (M21, 10E, 2X2, etc.).

    v3_v2 generated only alpha codes so the model had zero exposure to
    alphanumeric set codes. This test ensures the synthetic distribution
    now covers them.
    """
    specs = list(generate_specs(n=1000, seed=0))
    has_digit = sum(1 for s in specs if any(c.isdigit() for c in s.info_set))
    # Real distribution is ~33%. Allow wide tolerance.
    assert 200 < has_digit < 450, (
        f"only {has_digit}/1000 codes contain a digit (expected ~300-350)"
    )


def test_set_code_length_distribution_matches_reality() -> None:
    """Real Scryfall codes are ~43% 3-char and ~54% 4-char.

    v3_v2 weighted 3-char at 85% — wrong distribution that hurt 4-char
    accuracy at test time. Verify the new generator matches reality.
    """
    specs = list(generate_specs(n=2000, seed=0))
    lengths = Counter(len(s.info_set) for s in specs)
    pct3 = lengths[3] / len(specs)
    pct4 = lengths[4] / len(specs)
    # Tolerances to match real distribution within ±10pp.
    assert 0.33 < pct3 < 0.53, f"3-char rate {pct3:.2%} outside expected ~43% ±10pp"
    assert 0.44 < pct4 < 0.64, f"4-char rate {pct4:.2%} outside expected ~54% ±10pp"


def test_generate_specs_yields_n_specs() -> None:
    specs = list(generate_specs(n=100, seed=0))
    assert len(specs) == 100
    # Should be diverse — at least 3 different languages in 100 draws.
    langs = Counter(s.info_language for s in specs)
    assert len(langs) >= 3


def test_collector_number_formats_are_diverse() -> None:
    """Realistic distribution: most numeric, a few X-prefixed, some no /total."""
    specs = list(generate_specs(n=500, seed=0))
    has_slash = sum("/" in s.info_number for s in specs)
    has_x = sum(s.info_number.upper().startswith("X") for s in specs)
    # Majority should have /total (matches modern manifest distribution).
    assert has_slash > 200
    # X-prefix is rare but must exist (>0, <10% so not over-represented).
    assert 0 < has_x < 50


def test_collector_numbers_include_hyphen_format() -> None:
    """Promo + masterpiece cards use NNNN-N or LLL-NN style numbers.

    v3 model failed on these (e.g. predicted "201" for ground-truth "2025-1").
    Spec generator must emit them at a non-trivial rate so the model learns
    that hyphens are valid in the collector-number position.
    """
    specs = list(generate_specs(n=2000, seed=0))
    has_hyphen = sum("-" in s.info_number for s in specs)
    # Realistic distribution: ~5% of cards have hyphenated collector numbers.
    # We want at least 50 examples in 2000 specs to ensure the model sees them.
    assert has_hyphen > 50, f"only {has_hyphen}/2000 collector numbers contain '-'"


def test_collector_numbers_include_alpha_suffix() -> None:
    """Variant cards use NNNA suffix style (e.g. 042A, 118Z).

    v3 model failed on these. Spec generator must emit uppercase suffix forms
    so the model learns to read trailing letters in the collector-number slot.
    """
    specs = list(generate_specs(n=2000, seed=0))
    # Match `<digits><uppercase letter>` at the end of the collector-number string,
    # without a slash before it (we don't want to count rarity letters).
    import re

    pattern = re.compile(r"^[0-9]+[A-Z]$")
    has_alpha_suffix = sum(1 for s in specs if pattern.match(s.info_number))
    # Expected rate is 3% → ~60 in 2000 samples. Threshold of 30 leaves room
    # for natural variance + downstream rng consumption changes from set-code
    # generator iterations.
    assert has_alpha_suffix > 30, (
        f"only {has_alpha_suffix}/2000 collector numbers have alpha-suffix form"
    )


def test_foil_distribution_is_realistic() -> None:
    specs = list(generate_specs(n=1000, seed=0))
    foil_count = sum(s.foil for s in specs)
    # Real MTG distribution: foils are minority but not negligible.
    assert 100 < foil_count < 400


def test_generate_specs_with_adjacent_base_seeds_does_not_overlap() -> None:
    """Adjacent base seeds must produce essentially-disjoint streams.

    Regression test for a prior linear seed-mix bug where ``generate_specs(n, seed=0)``
    and ``generate_specs(n, seed=1)`` overlapped in 99% of specs.
    """
    a = list(generate_specs(n=100, seed=0))
    b = list(generate_specs(n=100, seed=1))
    overlap = sum(1 for spec_a, spec_b in zip(a, b, strict=True) if spec_a == spec_b)
    # Random chance of two specs being identical is roughly (1/N_sets) × (1/N_langs)
    # × (1/N_rarities) × (1/N_collectors) × 1/2 — vanishingly small. Allow up to 5
    # accidental collisions out of 100 to leave room for distribution-edge cases.
    assert overlap < 5, f"adjacent base seeds overlap {overlap}/100 — seed mixing is broken"
